active1:
  image: activemq:custom

  container_name: amq1

  environment:
    ROOT_LOGGER_LEVEL: DEBUG, console
    ACTIVEMQ_SPRING_LOGGER_LEVEL: DEBUG
    ACTIVEMQ_WEB_HANDLER_LOGGER_LEVEL: DEBUG
    SPRINGFRAMEWORK_LOGGER_LEVEL: DEBUG
    CAMEL_LOGGER_LEVEL: DEBUG
    CONSOLE_APPENDER_THRESHOLD_LEVEL: DEBUG
    NETWORK_OF_BROKERS_CONNECTORS_URI: static:(tcp:\/\/10.122.17.157:61617)

  ports:
    - 61616:61616

active2:
  image: activemq:custom

  container_name: amq2

  environment:
    ROOT_LOGGER_LEVEL: DEBUG, console
    ACTIVEMQ_SPRING_LOGGER_LEVEL: DEBUG
    ACTIVEMQ_WEB_HANDLER_LOGGER_LEVEL: DEBUG
    SPRINGFRAMEWORK_LOGGER_LEVEL: DEBUG
    CAMEL_LOGGER_LEVEL: DEBUG
    CONSOLE_APPENDER_THRESHOLD_LEVEL: DEBUG
    NETWORK_OF_BROKERS_CONNECTORS_URI: static:(tcp:\/\/10.122.17.157:61616)

  ports:
    - 61617:61616
